[package]
name = "catnip"
version = "0.1.0"
authors = ["skrytt"]
edition = "2018"

[dependencies]
dotenv = "0.14"
env_logger = "0.6"
log = "0.4"
rand = "0.7"
reqwest = "0.9"
rusqlite = "0.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serenity = "0.6"
time = "0.1"